### ISSUE TITLE
Change language with Cmd+Space

### ISSUE THREAD

**Issue by and7ey** [varp/karabiner-rdp#2]
Hello, is there any way to change the language within RDP with Mac command (Cmd+Space)? Don't see such action in your list.

PS. Many thanks for your configs!

**Comment by varp** [comment]
Hi @and7ey,
Cmd+Space will be directly translated to Win+Space, which switch keyboard layout since Windows 10 and versions of Windows Server based on it. So, for such systems, there is no need for such mapping. 

Because there is no approach for guessing the target system (Windows 10 or older) before translation, I have fixed Fn+Space mapping and added a new Cmd+Space as you requested. Look at https://github.com/varp/karabiner-rdp/blob/master/mac_osx_on_rdp.json#L639-L708. Enable one of them which you will desire. 

P.S. Please, don't forget to star the repo =)

**Comment by and7ey** [comment]
Thank you.
I am running MacOS 10.14.5 and Windows 10 Corporate thru RDP. If I press Cmd+Space, then it just shows the Start Menu.

And I am not sure how to import your updated config ;(..

**Comment by varp** [comment]
@and7ey Ohh, Just go to the Karabiner-Elements Preferences
1. Remove all modifications related to Mac OSX RDP one by one (see screenshot below)
![image](https://user-images.githubusercontent.com/504685/118849578-8a706300-b8d8-11eb-8f3b-111c550e2438.png)
2. Click Add Rule button and then find the Bin button against Mac OSX RDP and click it (see screenshot)
![image](https://user-images.githubusercontent.com/504685/118849878-d6bba300-b8d8-11eb-8c32-1b703417b638.png)
3. Click Import more rules from the Internet. Find my one ( Mac OSX RDP) and re-import again

**Comment by varp** [comment]
@and7ey At https://ke-complex-modifications.pqrs.org/?q=RDP
You should press Cmd+Shift+R to reload page skipping the local browser cache

**Comment by and7ey** [comment]
Many thanks. The local browser cache was the reason I wasn't able to install it myself.

Do I understand it correctly - it will work properly only if I change the input with Left Alt + Left Shift. And if I changed it to Left Ctrl + Left Shift, then it will not work? Could you please add such a combination to your repo?

**Comment by varp** [comment]
> Could you please add such a combination to your repo?

@and7ey done!

**Comment by and7ey** [comment]
Fantastic! Many thanks!
